services:
  insurgency-sandstorm:
    image: andrewmhub/insurgency-sandstorm:latest
    container_name: insurgency-sandstorm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./ismc2/config/ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer
      - ./ismc2/config/txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server
      - ./ismc2/mods:/home/steam/steamcmd/sandstorm/Insurgency/Mods
    ports:
      - "${PORT}:${PORT}/udp"
      - "${QUERYPORT}:${QUERYPORT}/udp"
